FROM jenkins/jenkins:2.492.3-lts-jdk21

# Change to the root user
USER root

# Install Docker CLI
RUN apt-get update \
    && apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
    && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt-get update \
    && apt-get install -y docker-ce-cli

# Add script to run when container starts. Will change permission on docker socket
COPY --chown=root:root jenkins-custom-entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/jenkins-custom-entrypoint.sh

# Switch back to the jenkins user so the container doesn't run as root
USER jenkins

# Skip the initial setup wizard
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

# Copy the plugins.txt file into the container
COPY jenkins-plugins.txt /usr/share/jenkins/ref/plugins.txt

# Install plugins using jenkins-plugin-cli
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt

# Use our custom entrypoint script
ENTRYPOINT ["/usr/local/bin/jenkins-custom-entrypoint.sh"]
