name: Build SPA

on:
  workflow_call:
  workflow_dispatch:

env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  
  Build-SPA:
    
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ github.workspace }}/react-spa

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Restore packages
        uses: volta-cli/action@v4
      
      - run: pnpm i
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
        