name: Build API

on:
  workflow_call:
  workflow_dispatch:

env:
  PUBLISH_DIR: ${{ github.workspace }}/publish/dotnet-api

jobs:
  
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ github.workspace }}/dotnet-api

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Publish
        working-directory: ${{ github.workspace }}/dotnet-api/BuildDeploy.Demo
        run: dotnet publish --configuration Release --no-build --output ${{ env.PUBLISH_DIR }}

      - name: Zip artifacts
        working-directory: ${{ env.PUBLISH_DIR }}
        run: zip -r ../dotnet-api-artifacts.zip .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-api-artifacts
          path: ./dotnet-api/dotnet-api-artifacts.zip
          retention-days: 1
