name: Build All

on:
  pull_request: 
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  
  build-api:
    uses: ./.github/workflows/build-api.yml
    
  build-spa:
    uses: ./.github/workflows/build-spa.yml
    needs: build-api
